typography_spectrum: 0.9370399252511561
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6379091781564057
  lightness: 0.7558940602466464
  saturation: 0.8702611979097128
  rhythmicContrast: 0.8968907168600708
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.15091737848706543
analytics:
  google: null
  facebook: null
  twitter: null
name: flmtss
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Technology & Learning Connections
description: Increasing student achievement through the systemi
purpose: []
